import {
  Client,
  AdminProject,
  ProjectStatus,
  PricingStatus,
  ProjectMessage,
  MessageType,
  SpendSummary,
} from "./types";

// Re-export types for convenience
export type { ProjectStatus, PricingStatus, MessageType, AdminProject, ProjectMessage, SpendSummary };

// Mock Projects
export const mockAdminProjects: AdminProject[] = [
  {
    id: "1",
    clientId: "c1",
    clientName: "Acme Corp",
    name: "Invoice Processing",
    version: "v1.0",
    type: "New Automation",
    status: "Live",
    checklistProgress: 100,
    pricingStatus: "Signed",
    owner: { name: "Sarah C.", avatar: "https://github.com/shadcn.png", role: "Solutions Engineer" },
    eta: "Oct 24",
    lastUpdated: "2024-10-24T10:00:00",
    lastUpdatedRelative: "2h ago",
    description: "OCR extraction from PDF invoices and sync with Xero.",
    systems: ["Xero", "Gmail", "Slack"],
    risk: "Low",
    estimatedVolume: 5000,
    setupFee: 1000,
    unitPrice: 0.045,
    effectiveUnitPrice: 0.045,
  },
  {
    id: "2",
    clientId: "c1",
    clientName: "Acme Corp",
    name: "Invoice Processing",
    version: "v1.1",
    type: "Revision",
    status: "Build in Progress",
    checklistProgress: 100,
    pricingStatus: "Signed",
    owner: { name: "Mike R.", avatar: "", role: "Solutions Engineer" },
    eta: "Nov 15",
    lastUpdated: "2024-11-01T09:30:00",
    lastUpdatedRelative: "10m ago",
    description: "Adding logic to handle invoices >$10k with a compliance check against sanctions list.",
    systems: ["Xero", "Gmail", "Slack", "OpenAI"],
    risk: "Low",
    estimatedVolume: 5000,
    setupFee: 1000,
    unitPrice: 0.045,
    effectiveUnitPrice: 0.0405,
  },
  {
    id: "3",
    clientId: "c2",
    clientName: "Globex Inc",
    name: "Employee Onboarding",
    version: "v1.0",
    type: "New Automation",
    status: "Needs Pricing",
    checklistProgress: 85,
    pricingStatus: "Draft",
    owner: { name: "Sarah C.", avatar: "https://github.com/shadcn.png", role: "Solutions Engineer" },
    eta: "TBD",
    lastUpdated: "2024-10-23T14:20:00",
    lastUpdatedRelative: "1d ago",
    description: "Provisioning accounts in Slack, Jira, and GSuite for new hires.",
    systems: ["Slack", "Jira", "GSuite"],
    risk: "Medium",
    estimatedVolume: 2000,
    setupFee: 1200,
    unitPrice: 0.05,
    effectiveUnitPrice: 0.05,
  },
  {
    id: "4",
    clientId: "c3",
    clientName: "Soylent Corp",
    name: "Lead Routing",
    version: "v2.0",
    type: "Revision",
    status: "Awaiting Client Approval",
    checklistProgress: 100,
    pricingStatus: "Sent",
    owner: { name: "Jessica P.", avatar: "", role: "Solutions Engineer" },
    eta: "Nov 20",
    lastUpdated: "2024-11-02T11:00:00",
    lastUpdatedRelative: "4h ago",
    description: "Updated lead scoring algorithm and routing rules.",
    systems: ["HubSpot", "Slack"],
    risk: "Low",
    estimatedVolume: 10000,
    setupFee: 800,
    unitPrice: 0.04,
    effectiveUnitPrice: 0.036,
  },
  {
    id: "5",
    clientId: "c4",
    clientName: "Umbrella Corp",
    name: "Compliance Check",
    version: "v1.0",
    type: "New Automation",
    status: "Intake in Progress",
    checklistProgress: 15,
    pricingStatus: "Not Generated",
    owner: { name: "Unassigned", avatar: "", role: "" },
    eta: "TBD",
    lastUpdated: "2024-11-03T08:00:00",
    lastUpdatedRelative: "Just now",
    description: "Automated compliance checks for new vendor onboarding.",
    systems: [],
    risk: "High",
  },
  {
    id: "6",
    clientId: "c5",
    clientName: "Stark Ind",
    name: "Part Requisition",
    version: "v3.1",
    type: "Revision",
    status: "QA & Testing",
    checklistProgress: 100,
    pricingStatus: "Signed",
    owner: { name: "Tony S.", avatar: "", role: "Solutions Engineer" },
    eta: "Nov 12",
    lastUpdated: "2024-11-02T16:45:00",
    lastUpdatedRelative: "30m ago",
    description: "Enhanced approval workflow for high-value parts.",
    systems: ["SAP", "Slack"],
    risk: "Medium",
    estimatedVolume: 3000,
    setupFee: 600,
    unitPrice: 0.035,
    effectiveUnitPrice: 0.035,
  },
  {
    id: "7",
    clientId: "c6",
    clientName: "Massive Dynamic",
    name: "Lab Analysis",
    version: "v1.0",
    type: "New Automation",
    status: "Ready to Launch",
    checklistProgress: 100,
    pricingStatus: "Signed",
    owner: { name: "Walter B.", avatar: "", role: "Solutions Engineer" },
    eta: "Today",
    lastUpdated: "2024-11-03T07:55:00",
    lastUpdatedRelative: "5m ago",
    description: "Automated analysis of lab results with AI classification.",
    systems: ["Lab System", "Slack", "OpenAI"],
    risk: "Low",
    estimatedVolume: 1500,
    setupFee: 1500,
    unitPrice: 0.06,
    effectiveUnitPrice: 0.06,
  },
];

// Mock Messages by Project ID
export const mockProjectMessages: Record<string, ProjectMessage[]> = {
  "1": [
    {
      id: "m1",
      projectId: "1",
      type: "client",
      sender: { name: "John Doe", role: "Client Lead" },
      text: "Hi team, just wanted to check if the new invoice threshold logic has been implemented yet?",
      timestamp: "Yesterday 2:30 PM",
    },
    {
      id: "m2",
      projectId: "1",
      type: "internal_note",
      sender: { name: "Mike Ross", role: "Solutions Engineer", avatar: "https://github.com/shadcn.png" },
      text: "Checking the blueprint now. I think we need to update the Filter node to handle >$10k specifically.",
      timestamp: "Yesterday 2:45 PM",
      tags: ["Blueprint Check"],
    },
    {
      id: "m3",
      projectId: "1",
      type: "ops",
      sender: { name: "Mike Ross", role: "Solutions Engineer", avatar: "https://github.com/shadcn.png" },
      text: "Hey John! We are finalizing that logic today. It will be ready for review by tomorrow morning.",
      timestamp: "Yesterday 2:50 PM",
    },
  ],
  "2": [
    {
      id: "m4",
      projectId: "2",
      type: "client",
      sender: { name: "John Doe", role: "Client Lead" },
      text: "Great, thanks Mike. Also attaching the updated sanctions list for reference.",
      timestamp: "Yesterday 3:00 PM",
      attachments: ["Sanctions_2025_v2.pdf"],
    },
    {
      id: "m5",
      projectId: "2",
      type: "internal_note",
      sender: { name: "Sarah C.", role: "Head of Ops", avatar: "https://github.com/shadcn.png" },
      text: "Needs verification of the Sanctions API rate limits. We might need to cache results.",
      timestamp: "2h ago",
      tags: ["Compliance Check"],
    },
  ],
  "3": [
    {
      id: "m6",
      projectId: "3",
      type: "client",
      sender: { name: "Jane Smith", role: "HR Director" },
      text: "When can we expect the onboarding automation to be ready?",
      timestamp: "1d ago",
    },
  ],
};

// Helper to get spend summary for a client
export function getClientSpendSummary(client: Client): SpendSummary {
  const clientProjects = mockAdminProjects.filter((p) => p.clientId === client.id);
  const committedMonthlySpend = client.committedSpend;
  const currentMonthSpend = client.activeSpend;
  const setupFeesCollected = clientProjects
    .filter((p) => p.pricingStatus === "Signed" && p.setupFee)
    .reduce((sum, p) => sum + (p.setupFee || 0), 0);
  const utilizationPercent = committedMonthlySpend > 0 
    ? Math.min((currentMonthSpend / committedMonthlySpend) * 100, 100)
    : 0;

  return {
    committedMonthlySpend,
    currentMonthSpend,
    setupFeesCollected,
    utilizationPercent,
  };
}

