import { Client } from "./types";

// Re-export for convenience
export type { Client };

export const mockClients: Client[] = [
  {
    id: "c1",
    name: "Acme Corp",
    industry: "Retail",
    activeSpend: 12500,
    committedSpend: 15000,
    activeProjects: 3,
    health: "Good",
    owner: { name: "Sarah C.", avatar: "https://github.com/shadcn.png" },
    lastActivity: "2h ago",
  },
  {
    id: "c2",
    name: "Globex Inc",
    industry: "Logistics",
    activeSpend: 4200,
    committedSpend: 10000,
    activeProjects: 1,
    health: "At Risk",
    owner: { name: "Mike R.", avatar: "" },
    lastActivity: "1d ago",
  },
  {
    id: "c3",
    name: "Soylent Corp",
    industry: "Manufacturing",
    activeSpend: 28000,
    committedSpend: 25000,
    activeProjects: 5,
    health: "Good",
    owner: { name: "Jessica P.", avatar: "" },
    lastActivity: "15m ago",
  },
  {
    id: "c4",
    name: "Massive Dynamic",
    industry: "R&D",
    activeSpend: 1500,
    committedSpend: 8000,
    activeProjects: 1,
    health: "Churn Risk",
    owner: { name: "Walter B.", avatar: "" },
    lastActivity: "5d ago",
  },
  {
    id: "c5",
    name: "Stark Ind",
    industry: "Defense",
    activeSpend: 85000,
    committedSpend: 80000,
    activeProjects: 8,
    health: "Good",
    owner: { name: "Tony S.", avatar: "" },
    lastActivity: "1h ago",
  },
  {
    id: "c6",
    name: "Cyberdyne",
    industry: "Technology",
    activeSpend: 5000,
    committedSpend: 5000,
    activeProjects: 2,
    health: "Good",
    owner: { name: "Sarah C.", avatar: "https://github.com/shadcn.png" },
    lastActivity: "3d ago",
  },
  {
    id: "c7",
    name: "Umbrella Corp",
    industry: "Pharma",
    activeSpend: 3200,
    committedSpend: 12000,
    activeProjects: 2,
    health: "At Risk",
    owner: { name: "Mike R.", avatar: "" },
    lastActivity: "2d ago",
  },
];
