import { z } from "zod";
import { type TemplateMetadata } from "@/lib/email/types";

const inviteSchema = z.object({
  firstName: z.string(),
  inviteLink: z.string().url(),
  workspaceName: z.string(),
});

export const templateRegistry: Record<string, TemplateMetadata<z.ZodTypeAny>> = {
  "transactional.workspace-invite": {
    templateId: "transactional.workspace-invite",
    category: "transactional",
    subject: "You’ve been invited to {{workspaceName}}",
    sender: "support",
    requiredVariables: inviteSchema,
    sampleVariables: {
      firstName: "Alex",
      inviteLink: "https://app.example.com/invite/abc123",
      workspaceName: "Acme Ops",
    },
    description: "Workspace invite email with magic link.",
    filePath: `${process.cwd()}/lib/email/templates/transactional/workspace-invite.html`,
  },
  "marketing.welcome": {
    templateId: "marketing.welcome",
    category: "marketing",
    subject: "Welcome to Wrk Copilot! 🚀",
    sender: "news",
    requiredVariables: z.object({
      firstName: z.string(),
      logoUrl: z.string().url(),
      ctaLink: z.string().url(),
      documentationLink: z.string().url(),
      unsubscribeLink: z.string().url(),
      privacyLink: z.string().url(),
      helpLink: z.string().url(),
      physicalAddress: z.string(),
      year: z.string(),
    }),
    sampleVariables: {
      firstName: "Sarah",
      logoUrl: "https://framerusercontent.com/images/6JnCZVCcfPnCQ8H5xwNdICaCSI.png",
      ctaLink: "https://app.wrkcopilot.com",
      documentationLink: "https://wrkcopilot.com/docs",
      unsubscribeLink: "https://wrkcopilot.com/unsubscribe",
      privacyLink: "https://wrkcopilot.com/privacy",
      helpLink: "https://wrkcopilot.com/help",
      physicalAddress: "1250 Rene-Levesque West, Montreal, Quebec, Canada",
      year: "2026",
    },
    description: "Welcome/onboarding marketing email with CTA to launch studio.",
    filePath: `${process.cwd()}/lib/email/templates/marketing/welcome.html`,
  },
  "transactional.user-invite": {
    templateId: "transactional.user-invite",
    category: "transactional",
    subject: "You’ve been invited to join {{workspaceName}}",
    sender: "support",
    requiredVariables: z.object({
      inviterName: z.string(),
      workspaceName: z.string(),
      inviteeEmail: z.string().email(),
      inviteLink: z.string().url(),
      unsubscribeLink: z.string().url(),
      privacyLink: z.string().url(),
      helpLink: z.string().url(),
      physicalAddress: z.string(),
      year: z.string(),
    }),
    sampleVariables: {
      inviterName: "Michael Scott",
      workspaceName: "Acme Corp",
      inviteeEmail: "pam.beesly@dundermifflin.com",
      inviteLink: "https://app.wrkcopilot.com/invite/accept",
      unsubscribeLink: "https://wrkcopilot.com/unsubscribe",
      privacyLink: "https://wrkcopilot.com/privacy",
      helpLink: "https://wrkcopilot.com/help",
      physicalAddress: "1250 Rene-Levesque West, Montreal, Quebec, Canada",
      year: "2026",
    },
    description: "User invite to a workspace.",
    filePath: `${process.cwd()}/lib/email/templates/transactional/user-invite.html`,
  },
  "notification.automation-deployed": {
    templateId: "notification.automation-deployed",
    category: "notification",
    subject: "Update: {{automationName}} is live",
    sender: "notifications",
    requiredVariables: z.object({
      automationName: z.string(),
      environment: z.string(),
      deployedBy: z.string(),
      deployedTime: z.string(),
      ctaLink: z.string().url(),
      unsubscribeLink: z.string().url(),
      privacyLink: z.string().url(),
      helpLink: z.string().url(),
      physicalAddress: z.string(),
      year: z.string(),
    }),
    sampleVariables: {
      automationName: "Invoice Processing v2.0",
      environment: "Production",
      deployedBy: "Sarah Chen",
      deployedTime: "Oct 24, 2:30 PM EST",
      ctaLink: "https://app.wrkcopilot.com/automations/123",
      unsubscribeLink: "https://wrkcopilot.com/unsubscribe",
      privacyLink: "https://wrkcopilot.com/privacy",
      helpLink: "https://wrkcopilot.com/help",
      physicalAddress: "1250 Rene-Levesque West, Montreal, Quebec, Canada",
      year: "2026",
    },
    description: "Automation deployed notification.",
    filePath: `${process.cwd()}/lib/email/templates/notification/automation-deployed.html`,
  },
  "transactional.invoice-receipt": {
    templateId: "transactional.invoice-receipt",
    category: "transactional",
    subject: "Receipt for your payment",
    sender: "support",
    requiredVariables: z.object({
      planName: z.string(),
      invoiceNumber: z.string(),
      invoiceDate: z.string(),
      invoiceItem: z.string(),
      invoiceAmount: z.string(),
      invoiceTotal: z.string(),
      downloadLink: z.string().url(),
      billingSupportLink: z.string().url(),
      unsubscribeLink: z.string().url(),
      privacyLink: z.string().url(),
      helpLink: z.string().url(),
      physicalAddress: z.string(),
      year: z.string(),
    }),
    sampleVariables: {
      planName: "Pro Plan",
      invoiceNumber: "INV-2024-001",
      invoiceDate: "Oct 24, 2024",
      invoiceItem: "Pro Plan (Monthly)",
      invoiceAmount: "$49.00",
      invoiceTotal: "$49.00",
      downloadLink: "https://app.wrkcopilot.com/invoices/123.pdf",
      billingSupportLink: "https://wrkcopilot.com/billing-support",
      unsubscribeLink: "https://wrkcopilot.com/unsubscribe",
      privacyLink: "https://wrkcopilot.com/privacy",
      helpLink: "https://wrkcopilot.com/help",
      physicalAddress: "1250 Rene-Levesque West, Montreal, Quebec, Canada",
      year: "2026",
    },
    description: "Payment receipt/invoice email.",
    filePath: `${process.cwd()}/lib/email/templates/transactional/invoice-receipt.html`,
  },
  "notification.workflow-chat-message": {
    templateId: "notification.workflow-chat-message",
    category: "notification",
    subject: "New message in {{workflowName}}",
    sender: "notifications",
    requiredVariables: z.object({
      recipientName: z.string(),
      workflowName: z.string(),
      messagePreview: z.string(),
      workflowUrl: z.string().url(),
      senderName: z.string(),
      unsubscribeLink: z.string().url(),
      privacyLink: z.string().url(),
      helpLink: z.string().url(),
      physicalAddress: z.string(),
      year: z.string(),
    }),
    sampleVariables: {
      recipientName: "Alex",
      workflowName: "Invoice Processing",
      messagePreview: "Hi, I have a question about the invoice processing workflow. Can we discuss the approval step?",
      workflowUrl: "https://app.wrkcopilot.com/automations/123",
      senderName: "Wrk Team",
      unsubscribeLink: "https://wrkcopilot.com/unsubscribe",
      privacyLink: "https://wrkcopilot.com/privacy",
      helpLink: "https://wrkcopilot.com/help",
      physicalAddress: "1250 Rene-Levesque West, Montreal, Quebec, Canada",
      year: "2026",
    },
    description: "Notification email for new workflow chat messages.",
    filePath: `${process.cwd()}/lib/email/templates/notification/workflow-chat-message.html`,
  },
};

export function getTemplate(templateId: string) {
  const template = templateRegistry[templateId];
  if (!template) {
    throw new Error(`Unknown email template: ${templateId}`);
  }
  return template;
}

